require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImportClientsController do

  # This should return the minimal set of attributes required to create a valid
  # ImportClient. As you add validations to ImportClient, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all import_clients as @import_clients" do
      import_client = ImportClient.create! valid_attributes
      get :index
      assigns(:import_clients).should eq([import_client])
    end
  end

  describe "GET show" do
    it "assigns the requested import_client as @import_client" do
      import_client = ImportClient.create! valid_attributes
      get :show, :id => import_client.id.to_s
      assigns(:import_client).should eq(import_client)
    end
  end

  describe "GET new" do
    it "assigns a new import_client as @import_client" do
      get :new
      assigns(:import_client).should be_a_new(ImportClient)
    end
  end

  describe "GET edit" do
    it "assigns the requested import_client as @import_client" do
      import_client = ImportClient.create! valid_attributes
      get :edit, :id => import_client.id.to_s
      assigns(:import_client).should eq(import_client)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImportClient" do
        expect {
          post :create, :import_client => valid_attributes
        }.to change(ImportClient, :count).by(1)
      end

      it "assigns a newly created import_client as @import_client" do
        post :create, :import_client => valid_attributes
        assigns(:import_client).should be_a(ImportClient)
        assigns(:import_client).should be_persisted
      end

      it "redirects to the created import_client" do
        post :create, :import_client => valid_attributes
        response.should redirect_to(ImportClient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved import_client as @import_client" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportClient.any_instance.stub(:save).and_return(false)
        post :create, :import_client => {}
        assigns(:import_client).should be_a_new(ImportClient)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportClient.any_instance.stub(:save).and_return(false)
        post :create, :import_client => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested import_client" do
        import_client = ImportClient.create! valid_attributes
        # Assuming there are no other import_clients in the database, this
        # specifies that the ImportClient created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImportClient.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => import_client.id, :import_client => {'these' => 'params'}
      end

      it "assigns the requested import_client as @import_client" do
        import_client = ImportClient.create! valid_attributes
        put :update, :id => import_client.id, :import_client => valid_attributes
        assigns(:import_client).should eq(import_client)
      end

      it "redirects to the import_client" do
        import_client = ImportClient.create! valid_attributes
        put :update, :id => import_client.id, :import_client => valid_attributes
        response.should redirect_to(import_client)
      end
    end

    describe "with invalid params" do
      it "assigns the import_client as @import_client" do
        import_client = ImportClient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportClient.any_instance.stub(:save).and_return(false)
        put :update, :id => import_client.id.to_s, :import_client => {}
        assigns(:import_client).should eq(import_client)
      end

      it "re-renders the 'edit' template" do
        import_client = ImportClient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportClient.any_instance.stub(:save).and_return(false)
        put :update, :id => import_client.id.to_s, :import_client => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested import_client" do
      import_client = ImportClient.create! valid_attributes
      expect {
        delete :destroy, :id => import_client.id.to_s
      }.to change(ImportClient, :count).by(-1)
    end

    it "redirects to the import_clients list" do
      import_client = ImportClient.create! valid_attributes
      delete :destroy, :id => import_client.id.to_s
      response.should redirect_to(import_clients_url)
    end
  end

end
